productcatalog:
  image: "thedanfernandez/productcatalog"
  ports: 
    - "80:80"
  tty: true
  links: 
    - elasticsearch
  environment: 
    - server.urls=http://0.0.0.0:80

elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"