productcatalog:
  image: "flakio/catalogservice:4"
  ports: 
    - "5000:5000"
  tty: true
  links: 
    - elasticsearch
  environment: 
    - server.urls=http://0.0.0.0:5000

elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
