apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalogservice
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: catalogservice
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalogservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalogservice
    spec:
      containers:
      - name: catalogservice
        image: flakio/catalogservice:8
        ports:
        - containerPort: 80
