apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalogservice
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: catalogservice
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalogservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalogservice
    spec:
      containers:
      - name: catalogservice
        image: flakio/catalogservice:8
        ports:
        - containerPort: 5000
        env: 
        - name: ELASTICSEARCH_PORT
          value: "http://elasticsearch-catalog:1025"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-catalog
  labels:
    app: elasticsearchcatalog
spec:
  type: ClusterIP
  ports:
  - port: 1025
  selector:
    app: elasticsearchcatalog
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearchcatalog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearchcatalog
    spec:
      containers:
      - name: elasticsearchcatalog
        image: elasticsearch:2.3.3
        ports:
        - containerPort: 1025
